### ISSUE TITLE
E2E Boilerplate

### ISSUE THREAD

**Issue by andreasonny83** [Online-Scoreboard/online-scoreboard#9]
**Describe the solution you'd like**
Create an E2E testing boilerplate using Selenium, Webdriver and CucumberJS for BDD.

**Describe alternatives you've considered**
A valid alternative would be using https://www.cypress.io/

**Additional context**
The testing script should be able to run inside a CircleCI environment to be run against each PR and validate the result

The initial boilerplate should just be able to navigate to the production URL of the app, verify the page title and exit

**Comment by kamolins** [comment]
Done in #27
